import os
import requests
import json
import datetime
from dotenv import load_dotenv

load_dotenv()

def log_interaction(request_payload, response_data, error=None):
    """Logs the interaction to a file for debugging."""
    log_dir = os.path.join(os.path.dirname(__file__), 'logs')
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)
    
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = {
        "timestamp": timestamp,
        "request": request_payload,
        "response": response_data,
        "error": error
    }
    
    log_file = os.path.join(log_dir, 'chatbot_api.log')
    with open(log_file, 'a', encoding='utf-8') as f:
        f.write(json.dumps(log_entry) + "\n")

def save_chat_history(history, session_id="default"):
    """Saves session chat history to a JSON file."""
    history_dir = os.path.join(os.path.dirname(__file__), 'logs', 'sessions')
    if not os.path.exists(history_dir):
        os.makedirs(history_dir)
    
    file_path = os.path.join(history_dir, f"{session_id}.json")
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(history, f, indent=2)

def load_chat_history(session_id="default"):
    """Loads session chat history from a JSON file."""
    file_path = os.path.join(os.path.dirname(__file__), 'logs', 'sessions', f"{session_id}.json")
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    return []

# We will read these within the function to ensure they are picked up if .env changes
# without a full app restart.

PROVIDERS = [
  {"label": "OpenAI", "value": "openai"},
  {"label": "Google", "value": "google"},
  {"label": "Claude", "value": "claude"}
]

LLM_MODELS = [
  {"provider": "openai", "label": "GPT-4o", "value": "gpt-4o"},
  {"provider": "openai", "label": "GPT-4o Mini", "value": "gpt-4o-mini"},
  {"provider": "openai", "label": "GPT-4 Turbo", "value": "gpt-4-turbo"},
  {"provider": "openai", "label": "GPT-3.5 Turbo", "value": "gpt-3.5-turbo"},
  {"provider": "google", "label": "Gemini 1.5 Pro", "value": "gemini-1.5-pro"},
  {"provider": "google", "label": "Gemini 1.5 Flash", "value": "gemini-1.5-flash"},
  {"provider": "claude", "label": "Claude 3.5 Sonnet", "value": "claude-3-5-sonnet-20240620"},
  {"provider": "claude", "label": "Claude 3 Opus", "value": "claude-3-opus-20240229"},
  {"provider": "claude", "label": "Claude 3 Haiku", "value": "claude-3-haiku-20240307"},
]

DEFAULT_LLM_MODEL = "gpt-4o"
DEFAULT_PROVIDER = "openai"

class DateTimeEncoder(json.JSONEncoder):
    """Custom JSON encoder to handle pandas Timestamps and datetimes."""
    def default(self, obj):
        if hasattr(obj, 'strftime'):
            return obj.strftime('%Y-%m-%d')
        return super().default(obj)

def build_system_prompt(data):
    return f"""
You are an AI-powered SAP business analyst assistant for a manufacturing company in India.
You have access to REAL model outputs generated by advanced AI
algorithms trained on the company's actual business data.

STRICT RULES:
- Always use the exact numbers from the data below. Never make up figures.
- Answer in plain English. No jargon.
- Always end every response with: "Action: [one specific thing to do today]"
- If asked to generate a report: cover all 5 sections clearly.
- If asked about a specific customer or product: find it in the data and be specific.
- Keep answers concise — max 6 lines unless a full report is requested.
- When listing multiple items (customers, products, SKUs, months), always provide a summary in a Markdown Table.
- **IMPORTANT**: The current system date is **2024-12-01**. 'Last month' means Nov 2024.
- If asked for a historical month (e.g. June 2023), look it up in the `historical_monthly_revenue` section provided below. If it's not there, say you don't have it.

══════════════════════════════════════════════
SALES FORECAST  (AI Confidence: {100.0 - data['sales']['xgboost_mape']}%)
══════════════════════════════════════════════
{json.dumps(data['sales'], indent=2, cls=DateTimeEncoder)}

══════════════════════════════════════════════
CASH FLOW & RECEIVABLES
══════════════════════════════════════════════
{json.dumps(data['cashflow'], indent=2, cls=DateTimeEncoder)}

══════════════════════════════════════════════
INVENTORY OPTIMIZATION
══════════════════════════════════════════════
{json.dumps(data['inventory'], indent=2, cls=DateTimeEncoder)}

══════════════════════════════════════════════
GST RECONCILIATION
══════════════════════════════════════════════
{json.dumps(data['gst'], indent=2, cls=DateTimeEncoder)}

══════════════════════════════════════════════
PROFITABILITY & CUSTOMER SEGMENTS
══════════════════════════════════════════════
{json.dumps(data['profitability'], indent=2, cls=DateTimeEncoder)}
"""

def call_ai_provider_orchestration(user_prompt, system_prompt, model_name=DEFAULT_LLM_MODEL, provider=DEFAULT_PROVIDER):
    """
    Calls the AI Provider Orchestration API.
    """
    # Read from environment each time to handle late .env additions
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    load_dotenv(dotenv_path=env_path)
    api_url = os.environ.get("AI_PROVIDER_ORCHESTRATION_API_URL", "")
    api_key = os.environ.get("AI_PROVIDER_ORCHESTRATION_API_KEY", "")

    if not api_url or not api_key:
        return {"error": "Missing API configuration in .env"}
    
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }
    
    payload = {
        "model": model_name,
        "provider": provider,
        "prompts": [system_prompt, user_prompt]
    }
    
    try:
        # Construct the URL, ensuring no double slashes
        base_url = api_url.rstrip('/')
        target_url = f"{base_url}/ai/generate"
        response = requests.post(target_url, headers=headers, json=payload, timeout=30)
        
        # Log successful (or status-error) response
        log_interaction(payload, {"status": response.status_code, "text": response.text})
        
        response.raise_for_status()
        return response.json()
    except Exception as e:
        # Log exception
        log_interaction(payload, None, error=str(e))
        return {"error": str(e)}

def ask(question, history, data, model_name=DEFAULT_LLM_MODEL, provider=DEFAULT_PROVIDER):
    """
    Hybrid NLP layer: tries the real AI Orchestration API first, 
    falls back to hardcoded 'POC' logic if the API is unavailable.
    """
    q = question.lower()

    # 1. IMMEDIATE HISTORICAL DATA OVERRIDE
    # (Checking for specific months/years first to ensure 'Brutally Honest' accuracy)
    months_map = {"jan": "01", "feb": "02", "mar": "03", "apr": "04", "may": "05", "jun": "06", 
                  "jul": "07", "aug": "08", "sep": "09", "oct": "10", "nov": "11", "dec": "12"}
    
    target_month = None
    if "202" in q: # Quick filter for year
        for m_name, m_num in months_map.items():
            if m_name in q:
                for year in ["2022", "2023", "2024"]:
                    if year in q:
                        target_month = f"{year}-{m_num}"
                        break
    
    if target_month:
        hist_data = data['sales'].get('historical_monthly_revenue', {})
        val = hist_data.get(target_month)
        if val:
            return f"**AI Assistant:**\n For **{target_month}**, the total recorded revenue was **₹{int(val):,}**.\n\n**Action:** Compare this to the current month's performance in the 'Sales Forecast' panel."
        else:
            return f"**AI Assistant:**\n I am sorry, but my records for NK Protein do not contain specific revenue data for **{target_month}**. My data spans from Jan 2022 to Dec 2024.\n\n**Action:** Please consult the SAP Archive for older financial records."

    # 2. Attempt Real AI Orchestration
    system_prompt = {"role": "system", "content": build_system_prompt(data)}
    user_prompt   = {"role": "user", "content": question}
    
    ai_response = call_ai_provider_orchestration(user_prompt, system_prompt, model_name, provider)
    
    if isinstance(ai_response, dict):
        # 2a. Standard OpenAI format
        if "choices" in ai_response and len(ai_response["choices"]) > 0:
            content = ai_response["choices"][0].get("message", {}).get("content", "")
            if content:
                return content
        
        # 2b. Custom Orchestration format (as seen in logs)
        if "response" in ai_response:
            content = ai_response["response"]
            if content:
                return content
            
    # Capture error if any
    api_error = ai_response.get("error") if isinstance(ai_response, dict) else None

    # 3. Fallback to Hardcoded POC Logic (The main POC work)
    if "predict" in q or "sales" in q or "quarter" in q or "revenue" in q:
        next_month_sales = int(data['sales']['forecast_next_3_months'][0]['yhat']) if data['sales']['forecast_next_3_months'] else 0
        trend = data['sales']['trend']
        top_product = data['sales']['top_5_products'][0].get('product_name', 'your top product') if data['sales']['top_5_products'] else 'Unknown'
        
        if trend == "upward":
            action_text = f"Increase production of **{top_product}** to capitalize on expected demand."
        else:
            action_text = f"Optimize inventory and reduce over-purchasing for **{top_product}** to defend against the {trend} trajectory."
            
        # Create Table
        table = "| Month | Forecasted Revenue | Trend |\n| :--- | :--- | :--- |\n"
        for m in data['sales']['forecast_next_3_months']:
            month_str = m['ds'][:7] # YYYY-MM
            table += f"| {month_str} | ₹{int(m['yhat']):,} | {trend} |\n"

        return f"**AI Assistant:**\n Based on our predictive AI engine, sales are forecast to move in a {trend} direction.\n\n{table}\n\n**Action:** {action_text}"

    elif "cash flow" in q or "overdue" in q or "trapped" in q or "paying" in q or "receivable" in q or "dso" in q:
        overdue_amt = data['cashflow']['total_overdue']
        top_payers = data['cashflow']['top_slow_payers']
        if top_payers:
            # Create Table
            table = "| Customer | Total Overdue | Days Late |\n| :--- | :--- | :--- |\n"
            for p in top_payers:
                table += f"| {p.get('customer_name', 'Unknown')} | ₹{int(p.get('total_overdue', 0)):,} | {p.get('avg_days_late', 0):.1f} |\n"
            data_disp = f"\n\n{table}"
        else:
            data_disp = "\n\nNo critical slow payers identified."

        return f"**AI Assistant:**\n You currently have **₹{overdue_amt:,}** trapped in overdue receivables. Your overall collection period (DSO) is {data['cashflow']['dso_days']} days.{data_disp}\n\n**Action:** Immediately review credit terms and send payment reminders for your top offenders."

    elif "discontinue" in q or "margin" in q or "product" in q:
        bad_prods = data['profitability']['products_to_discontinue']
        low_margin_customers = data['profitability']['renegotiate_count']
        
        if bad_prods:
            # Create Table
            table = "| Product | Net Margin % | Risk Level |\n| :--- | :--- | :--- |\n"
            for p in bad_prods:
                table += f"| {p.get('product_name', 'Unknown')} | {p.get('net_margin_pct', 0)}% | High Risk |\n"
            data_disp = f"\n\n{table}"
            action_text = f"Phase out these low-margin products to immediately free up working capital."
        else:
            data_disp = ""
            action_text = "Review all product margins and evaluate the 'Low Margin Risk' customer segment for contract renegotiation."
            
        return f"**AI Assistant:**\n Our unit economics AI calculates margins and has flagged {low_margin_customers} customers operating in the 'Low Margin Risk' segment.{data_disp}\n\n**Action:** {action_text}"

    elif "gst" in q or "tax" in q or "mismatch" in q:
        mismatches = data['gst']['total_mismatches']
        itc_risk = data['gst']['total_itc_at_risk']
        top_risks = data['gst']['top_supplier_risks']
        
        if top_risks:
            # Create Table
            table = "| Supplier | Invoices | ITC at Risk |\n| :--- | :--- | :--- |\n"
            for r in top_risks:
                table += f"| {r.get('supplier_name', 'Unknown')} | {r.get('invoice_count', 0)} | ₹{int(r.get('total_itc_risk', 0)):,} |\n"
            data_disp = f"\n\n{table}"
        else:
            data_disp = ""

        return f"**AI Assistant:**\n Our anomaly detection AI identified **{mismatches} GST mismatches** compared to your internal books, putting **₹{itc_risk:,}** of Input Tax Credit (ITC) at risk.{data_disp}\n\n**Action:** Reconcile the invoices highlighted as high-risk anomalies this month."

    elif "dead" in q or "stock" in q or "inventory" in q or "liquidate" in q:
        dead_skus = data['inventory']['dead_stock_count']
        capital = data['inventory']['total_capital_locked']
        top_dead = data['inventory']['top_dead_skus']
        
        if top_dead:
            # Create Table
            table = "| SKU | Warehouse | Days Idle | Capital Locked |\n| :--- | :--- | :--- | :--- |\n"
            for d in top_dead:
                table += f"| {d.get('sku', 'Unknown')} | {d.get('warehouse', 'N/A')} | {d.get('days_no_movement', 0)} | ₹{int(d.get('capital_locked', 0)):,} |\n"
            data_disp = f"\n\n{table}"
            action_text = f"Prioritize liquidating these top offenders to improve your cash position."
        else:
            data_disp = ""
            action_text = "Liquidate completely idle SKUs to improve your cash position."
            
        return f"**AI Assistant:**\n You currently have **{dead_skus}** dead stock SKUs collectively locking up **₹{capital:,}** in working capital.{data_disp}\n\n**Action:** {action_text}"

    elif "report" in q:
        # Sales
        next_month = int(data['sales']['forecast_next_3_months'][0]['yhat'])
        # Cashflow
        overdue = data['cashflow']['total_overdue']
        dso = data['cashflow']['dso_days']
        # Inventory
        dead_cap = data['inventory']['total_capital_locked']
        # GST
        gst_risk = data['gst']['total_itc_at_risk']
        # Profitability
        low_margin = data['profitability']['renegotiate_count']

        report = (
            "**NK Protein Executive Summary Report**\n\n"
            f"1. **Sales:** Forecast for next month is **₹{next_month:,}** ({data['sales']['trend']} trend).\n"
            f"2. **Cash Flow:** **₹{overdue:,}** overdue (DSO: {dso} days).\n"
            f"3. **Inventory:** **₹{dead_cap:,}** locked in dead stock.\n"
            f"4. **GST:** **₹{gst_risk:,}** ITC at risk due to mismatches.\n"
            f"5. **Profitability:** {low_margin} customers identified for margin renegotiation.\n\n"
            "**Action:** Review the deep-dive panels above for specific SKU and customer lists."
        )
        return f"**AI Assistant:**\n{report}"

    else:
        # Check if API is actually configured
        env_path = os.path.join(os.path.dirname(__file__), '.env')
        load_dotenv(dotenv_path=env_path)
        api_url = os.environ.get("AI_PROVIDER_ORCHESTRATION_API_URL", "")
        api_key = os.environ.get("AI_PROVIDER_ORCHESTRATION_API_KEY", "")
        
        if not api_url or not api_key:
            return f"**AI Assistant:** I am currently running in **offline mock mode** because the API configuration (URL/Key) is missing in your `.env` file. Please ensure `AI_PROVIDER_ORCHESTRATION_API_URL` and `AI_PROVIDER_ORCHESTRATION_API_KEY` are set.\n\nHowever, the data panels above reflect the **real calculations** from your dynamic datasets! Try asking about 'sales' or 'cash flow'."
        
        error_msg = f" (Error: {api_error})" if api_error else ""
        return f"**AI Assistant:** I encountered an issue connecting to the AI Orchestration API{error_msg}. Falling back to POC logic. Try asking about 'sales', 'inventory', or 'GST' to see the calculated insights."

